@startuml
title Diagramme d'état - Jeu Géometry Dash
[*] --> Vivant

state Vivant {
    Vivant -d-> Cube

    state Cube {
        Grounded -l-> Jumping : Jump
        Jumping -r-> Grounded : Touch_Ground
    }

    state Ship {
        Flying -l-> Falling
        Falling -r-> Flying 
    }

    state Wave {
        GoUp -l-> GoDown 
        GoDown -r-> GoUp 
    }

    Ship -l-> Cube : ChangeGameMode
    Cube -r-> Ship : ChangeGameMode
    Wave --> Cube : ChangeGameMode
    Cube --> Wave : ChangeGameMode
    Ship --> Wave : ChangeGameMode
    Wave -l-> Ship : ChangeGameMode
}

Vivant --> Mort : Collide
Mort --> [*]

@enduml